---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 24/01/2019 00:13
---

_menuPool = NativeUI.CreatePool()

mainMenu = NativeUI.CreateMenu("NativeUILua", "~b~NATIVEUI SHOWCASE", nil, nil, nil, nil, nil, 255, 255, 255, 255)

_menuPool:Add(mainMenu)

function OpenMainHeritageUI(menu)
    local amount = {}

    for i = 1, 10 do
        amount[i] = i
    end

    menu:PageCounterName("~r~NATIVEUILUA")
    local submenu = _menuPool:AddSubMenu(menu, "Another Menu")
    for i = 1, 20, 1 do

        submenu.SubMenu:AddItem(NativeUI.CreateItem("PageFiller", "Sample description that takes more than one line. Moreso, it takes way more than two lines since it's so long. Wow, check out this length!"))
    end
    --[[
    local CreateSliderHeritageItem = NativeUI.CreateSliderHeritageItem("Resemblance", amount, 5, "")
    menu:AddItem(CreateSliderHeritageItem)

    CreateSliderHeritageItem.OnSliderChanged = function(menu, item, newindex)
        UIVisual:Text({
            message = newindex
        })
    end
    ]]


end

function SexHeritageUI(menu)

end

function HeritageUI(menu)

end

function FeaturesUI(menu)

end

function AppearanceUI(menu)

end

function ApparelUI(menu)

end

OpenMainHeritageUI(mainMenu)

_menuPool:RefreshIndex()

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(1)
        _menuPool:ProcessMenus()
        if IsControlJustPressed(1, 51) then
            mainMenu:Visible(not mainMenu:Visible())
        end
    end
end)