---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 20/12/2019 22:32
---
fx_version 'adamant'
games { 'gta5' };

name 'NativeUILua-Reloaded'
description 'NativeUILua-Reloaded is UI library for FiveM designed specifically for making interface based on GTA:Online style. (Base source: https://github.com/FrazzIe/NativeUILua ) | (Base NativeUI : https://github.com/Guad/NativeUI) '

contributor {
    'Dylan Malandain',
    'Parow',
    'Frazzle'
};

client_scripts {
    "Wrapper/*.lua",
    "UIElements/*.lua",
}

client_scripts {
    "UIMenu/elements/*.lua",
    "UIMenu/items/*.lua",
    "UIMenu/windows/*.lua",
    "UIMenu/panels/*.lua",
    "UIMenu/*.lua",
}

client_scripts {
    'UITimerBar/*.lua',
    'UITimerBar/items/*.lua',
}

client_scripts {
    'UIProgressBar/*.lua',
    'UIProgressBar/items/*.lua',
}

client_scripts {
    "NativeUI.lua",
}
