---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 26/01/2019 17:36
---

TimerBarPool = setmetatable({}, TimerBarPool)
TimerBarPool.__index = TimerBarPool

---New
function TimerBarPool.New()
    local _TimerBarPool = {
        TimerBars = {}
    }
    return setmetatable(_TimerBarPool, TimerBarPool)
end

function TimerBarPool:Draw()
    --print('alo ?')
    for _, TimerBar in pairs(self.TimerBars) do
        TimerBar:Draw()
    end
end
