---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 26/01/2019 17:36
---
-- TODO Realiser le systeme de Padding automatique ect...
UITimerBar = setmetatable({}, UITimerBar)
UITimerBar.__index = UITimerBar
UITimerBar.__call = function()
    return "UITimerBar"
end

function UITimerBar.New(TxtDictionary, TxtName, X, Y, Heading, R, G, B, A)
    local X, Y = tonumber(X) or 0, tonumber(Y) or 0
    if TxtDictionary ~= nil then
        TxtDictionary = tostring(TxtDictionary) or "timerbars"
    else
        TxtDictionary = "timerbars"
    end
    if TxtName ~= nil then
        TxtName = tostring(TxtName) or "all_black_bg"
    else
        TxtName = "all_black_bg"
    end
    if Heading ~= nil then
        Heading = tonumber(Heading) or 0
    else
        Heading = 0
    end
    if R ~= nil then
        R = tonumber(R) or 255
    else
        R = 255
    end
    if G ~= nil then
        G = tonumber(G) or 255
    else
        G = 255
    end
    if B ~= nil then
        B = tonumber(B) or 255
    else
        B = 255
    end
    if A ~= nil then
        A = tonumber(A) or 150
    else
        A = 150
    end
    local _UITimerBar = {
        Background = Sprite.New(TxtDictionary, TxtName, 0, 0, 250, 45, Heading, R, G, B, A),
        Position = { X = 1630, Y = 1050 },
    }
    return setmetatable(_UITimerBar, UITimerBar)
end

function UITimerBar:Draw(Interval)

    self.Background:Position(self.Position.X, self.Position.Y - Interval)

    self.Background:Draw()
end

