---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 26/01/2019 17:36
---
TimerBarPool = setmetatable({}, TimerBarPool)
TimerBarPool.__index = TimerBarPool

function TimerBarPool.New()
    local _TimerBarPool = {
        TimerBars = {},
        _Limite = 20
    }
    return setmetatable(_TimerBarPool, TimerBarPool)
end

function TimerBarPool:Add(TimerBar)
    if TimerBar() == "UITimerBar" then
        table.insert(self.TimerBars, TimerBar)
    end
end

function TimerBarPool:Draw()
    for _, TimerBar in pairs(self.TimerBars) do
        TimerBar:Draw(50 * _)
    end
end