---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 26/01/2019 17:36
---
-- TODO Realiser le systeme de POOL + Draw du UITimerBarPool + D'autre utilitaire
TimerBarPool = setmetatable({}, TimerBarPool)
TimerBarPool.__index = TimerBarPool

function TimerBarPool.New()
    local _TimerBarPool = {
        TimerBars = {},
    }
    return setmetatable(_TimerBarPool, TimerBarPool)
end

function TimerBarPool:Add(TimerBar)
    if TimerBar() == "TimerBarProgressItem" then
        table.insert(self.TimerBars, TimerBar)
    end
end

function TimerBarPool:ProcessTimerBar()
    self:Draw()
end