---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 26/01/2019 17:38
---
TimerBarProgressItem = setmetatable({}, TimerBarProgressItem)
TimerBarProgressItem.__index = TimerBarProgressItem
TimerBarProgressItem.__call = function()
    return "TimerBarProgressItem"
end

function TimerBarProgressItem.New()
    local _TimerBarProgressItem = {
        Background = Sprite.New("timerbars", "all_black_bg", 0, 0, 270, 40, 0, 255, 255, 255, 150),
        _Bar = { Width = 1600, Height = 1000 },
        _Offset = { X = 0, Y = 0 },
    }
    return setmetatable(_TimerBarProgressItem, TimerBarProgressItem)
end

function TimerBarProgressItem:Offset(X, Y)
    if tonumber(X) or tonumber(Y) then
        if tonumber(X) then
            self._Offset.X = tonumber(X)
        end
        if tonumber(Y) then
            self._Offset.Y = tonumber(Y)
        end
    else
        return self._Offset
    end
end

function TimerBarProgressItem:Position(Y)
    if tonumber(Y) then
        self.Background:Position(self._Offset.X, Y + 144 + self._Offset.Y)
    end
end

function TimerBarProgressItem:Draw()
    self.Background:Draw()
end